Repository QuantestPy/quantestpy, pull requests merged in 2023-02, with the labels that each got.

#199 Prepare for using PyPI
  .github/workflows/python-publish.yml
  README.md
  pyproject.toml
  quantestpy/__init__.py
Labels: feedback submitted

#196 Update docs and Readme
  README.md
  doc/assertion/assert_ancilla_reset.md
  doc/assertion/assert_circuit_equivalent_to_operator.md
  doc/assertion/assert_circuit_equivalent_to_output_qubit_state.md
  doc/assertion/assert_equivalent_circuits.md
  doc/assertion/assert_equivalent_operators.md
  doc/assertion/assert_equivalent_state_vectors.md
  doc/assertion/assert_normalized_state_vector.md
  doc/assertion/assert_qubit_reset_to_zero_state.md
  doc/assertion/assert_unary_iteration.md
  doc/assertion/assert_unitary_operator.md
  doc/assertion/fig/assert_circuit_equivalent_to_output_qubit_state_0.PNG
  doc/assertion/fig/assert_unary_iteration_0.PNG
  doc/get_ctrl_val.md
  doc/pauli_circuit.md
  doc/pauli_circuit_add_gate.md
  doc/pauli_circuit_draw.md
  doc/pauli_circuit_set_qubit_value.md
  doc/simulator/quantestpy_circuit.md
  doc/simulator/quantestpy_circuit_add_gate.md
  doc/simulator/quantestpy_circuit_draw.md
  doc/test_circuit.md
  doc/test_circuit_set_initial_state_vector.md
Labels: ready for reviews, feedback submitted

#198 Add sample codes using assert_unary_iteration() and assert_circuit_equivalent_to_output_qubit_state()
  sample/adder.py
  sample/basic_unary_iteration.py
  sample/indexed_Majorana.py
  sample/ranged_unary_iteration.py
Labels: ready for reviews, feedback submitted

#202 Fix a bug in draw_wire method
  quantestpy/visualization/quantestpy_circuit_drawer.py
  test/visualization/quantestpy_circuit_drawer/test_draw_wire.py
Labels: ready for reviews

#203 Implement control gates in Qiskit
  quantestpy/converter/sdk/qiskit.py
  quantestpy/simulator/state_vector_circuit.py
  test/with_qiskit/simulator/__init__.py
  test/with_qiskit/simulator/state_vector_circuit/__init__.py
  test/with_qiskit/simulator/state_vector_circuit/test_h_gate.py
  test/with_qiskit/simulator/state_vector_circuit/test_id_gate.py
  test/with_qiskit/simulator/state_vector_circuit/test_iswap_gate.py
  test/with_qiskit/simulator/state_vector_circuit/test_p_gate.py
  test/with_qiskit/simulator/state_vector_circuit/test_r_gate.py
  test/with_qiskit/simulator/state_vector_circuit/test_rx_gate.py
  test/with_qiskit/simulator/state_vector_circuit/test_ry_gate.py
  test/with_qiskit/simulator/state_vector_circuit/test_rz_gate.py
  test/with_qiskit/simulator/state_vector_circuit/test_s_gate.py
  test/with_qiskit/simulator/state_vector_circuit/test_sdg_gate.py
  test/with_qiskit/simulator/state_vector_circuit/test_swap_gate.py
  test/with_qiskit/simulator/state_vector_circuit/test_sx_gate.py
  test/with_qiskit/simulator/state_vector_circuit/test_sxdg_gate.py
  test/with_qiskit/simulator/state_vector_circuit/test_u_gate.py
  test/with_qiskit/simulator/state_vector_circuit/test_x_gate.py
  test/with_qiskit/simulator/state_vector_circuit/test_y_gate.py
  test/with_qiskit/simulator/state_vector_circuit/test_z_gate.py
Labels: ready for reviews

#208 An appropriate error happens when converter gets unknown gates.
  quantestpy/converter/sdk/qiskit.py
  test/with_qiskit/converter/__init__.py
  test/with_qiskit/converter/sdk/__init__.py
  test/with_qiskit/converter/sdk/test_qiskit.py
Labels: ready for reviews, feedback submitted
